/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JOptionPane;


/*
 * accView.java
 *
 * Created on oct 30, 2013, 7:14:21 PM
 */

/**
 *
 * @author admin
 */
public class accView extends javax.swing.JFrame {

    /** Creates new form accView */
    public accView() {
        initComponents();
    }
 Statement stmt=null;
ResultSet rs=null;
 String SQL="SELECT * FROM CUSTOMER";
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j3 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j1 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        j6 = new javax.swing.JTextField();
        jSex = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jStatus = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jType = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nxtBtn = new javax.swing.JButton();
        preBtn = new javax.swing.JButton();
        lstBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        fstBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel6.setText("Status");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel5.setText("Sex");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel11.setText("Account Number");

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 3, 14));
        jLabel24.setText("Personal Income");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel3.setText("Husband/Fathers Name");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 3, 14));
        jLabel10.setText("Type Of A/C");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setText("Account Holders Name");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel4.setText("Date of Birth");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 14));
        jLabel7.setText("Age");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel8.setText("A/c Opening Date");

        nxtBtn.setText("Next");
        nxtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtBtnActionPerformed(evt);
            }
        });

        preBtn.setText("Previous");
        preBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preBtnActionPerformed(evt);
            }
        });

        lstBtn.setText("Last");
        lstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstBtnActionPerformed(evt);
            }
        });

        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        fstBtn.setText("First");
        fstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fstBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(fstBtn)
                .addGap(27, 27, 27)
                .addComponent(nxtBtn)
                .addGap(18, 18, 18)
                .addComponent(preBtn)
                .addGap(18, 18, 18)
                .addComponent(lstBtn)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(287, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(303, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel24))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(254, 254, 254)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(j1)
                        .addComponent(j2)
                        .addComponent(j3)
                        .addComponent(j4)
                        .addComponent(jSex)
                        .addComponent(j5)
                        .addComponent(jStatus)
                        .addComponent(j7, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                        .addComponent(jType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(lstBtn)
                    .addComponent(preBtn)
                    .addComponent(nxtBtn)
                    .addComponent(fstBtn))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(49, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fstBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/PROJECT","root","bhaba");
             stmt=con.createStatement();
            rs=stmt.executeQuery(SQL);

            if(rs.first()){
                String accf=rs.getString("Accno");
                 String ahname=rs.getString("AHNAME");
                String hname=rs.getString("HNAME");
                String dob=rs.getString("DOB");
                String pi=rs.getString("PI");
                String acdate=rs.getString("ACDATE");
                String age=rs.getString("AGE");
               String sex=rs.getString("SEX");
               String status=rs.getString("STATUS");
               String type=rs.getString("ACCTYP");

                j1.setText(accf);
                j2.setText(ahname);
                j3.setText(hname);
                j4.setText(dob);
                j5.setText(age);
                j6.setText(pi);
                j7.setText(acdate);
               j1.setEditable(false);
              jSex.setText(sex);
              jStatus.setText(status);
              jType.setText(type);

              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(true);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(true);
            }
            else{
              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(false);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(false);
              JOptionPane.showMessageDialog(null,"Record not found in customer table");
            }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_fstBtnActionPerformed

    private void preBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preBtnActionPerformed
        // TODO add your handling code here:
          try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/PROJECT","root","");
            stmt=con.createStatement();
            rs=stmt.executeQuery(SQL);

            if(rs.previous()){
                String accf=rs.getString("Accno");
                 String ahname=rs.getString("AHNAME");
                String hname=rs.getString("HNAME");
                String dob=rs.getString("DOB");
                String pi=rs.getString("PI");
                String acdate=rs.getString("ACDATE");
                String age=rs.getString("AGE");
               String sex=rs.getString("SEX");
               String status=rs.getString("STATUS");
               String type=rs.getString("ACCTYP");

                j1.setText(accf);
                j2.setText(ahname);
                j3.setText(hname);
                j4.setText(dob);
                j5.setText(age);
                j6.setText(pi);
                j7.setText(acdate);
               j1.setEditable(false);
              jSex.setText(sex);
              jStatus.setText(status);
              jType.setText(type);

              fstBtn.setEnabled(true);
              nxtBtn.setEnabled(true);
              preBtn.setEnabled(true);
              lstBtn.setEnabled(true);
            }
            else{
              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(false);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(false);
              JOptionPane.showMessageDialog(null,"Record not found in customer table");
            }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_preBtnActionPerformed

    private void nxtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtBtnActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/PROJECT","root","");
             stmt=con.createStatement();
            rs=stmt.executeQuery(SQL);

            if(rs.next()){
                String accf=rs.getString("Accno");
                 String ahname=rs.getString("AHNAME");
                String hname=rs.getString("HNAME");
                String dob=rs.getString("DOB");
                String pi=rs.getString("PI");
                String acdate=rs.getString("ACDATE");
                String age=rs.getString("AGE");
               String sex=rs.getString("SEX");
               String status=rs.getString("STATUS");
               String type=rs.getString("ACCTYP");

                j1.setText(accf);
                j2.setText(ahname);
                j3.setText(hname);
                j4.setText(dob);
                j5.setText(age);
                j6.setText(pi);
                j7.setText(acdate);
               j1.setEditable(false);
              jSex.setText(sex);
              jStatus.setText(status);
              jType.setText(type);

              fstBtn.setEnabled(true);
              nxtBtn.setEnabled(true);
              preBtn.setEnabled(true);
              lstBtn.setEnabled(true);
            }
            else{
              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(false);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(false);
              JOptionPane.showMessageDialog(null,"Record not found in customer table");
            }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_nxtBtnActionPerformed

    private void lstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstBtnActionPerformed

          try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/PROJECT","root","");
             stmt=con.createStatement();
            rs=stmt.executeQuery(SQL);

            if(rs.last()){
                String accf=rs.getString("Accno");
                 String ahname=rs.getString("AHNAME");
                String hname=rs.getString("HNAME");
                String dob=rs.getString("DOB");
                String pi=rs.getString("PI");
                String acdate=rs.getString("ACDATE");
                String age=rs.getString("AGE");
               String sex=rs.getString("SEX");
               String status=rs.getString("STATUS");
               String type=rs.getString("ACCTYP");

                j1.setText(accf);
                j2.setText(ahname);
                j3.setText(hname);
                j4.setText(dob);
                j5.setText(age);
                j6.setText(pi);
                j7.setText(acdate);
               j1.setEditable(false);
              jSex.setText(sex);
              jStatus.setText(status);
              jType.setText(type);

              fstBtn.setEnabled(true);
              nxtBtn.setEnabled(true);
              preBtn.setEnabled(true);
              lstBtn.setEnabled(true);
            }
            else{
              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(false);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(false);
              JOptionPane.showMessageDialog(null,"Record not found in customer table");
            }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_lstBtnActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
 try {
       Class.forName("com.mysql.jdbc.Driver");
       Connection con=(Connection)
       DriverManager.getConnection("jdbc:mysql://localhost:3306/PROJECT","root","");
        stmt=con.createStatement();
            rs=stmt.executeQuery(SQL);

       if(rs.first()){
                String accf=rs.getString("Accno");
                 String ahname=rs.getString("AHNAME");
                String hname=rs.getString("HNAME");
                String dob=rs.getString("DOB");
                String pi=rs.getString("PI");
                String acdate=rs.getString("ACDATE");
                String age=rs.getString("AGE");
               String sex=rs.getString("SEX");
               String status=rs.getString("STATUS");
               String type=rs.getString("ACCTYP");

                j1.setText(accf);
                j2.setText(ahname);
                j3.setText(hname);
                j4.setText(dob);
                j5.setText(age);
                j6.setText(pi);
                j7.setText(acdate);
               j1.setEditable(false);
              jSex.setText(sex);
              jStatus.setText(status);
              jType.setText(type);

              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(true);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(true);
            }
            else{
              fstBtn.setEnabled(false);
              nxtBtn.setEnabled(false);
              preBtn.setEnabled(false);
              lstBtn.setEnabled(false);
              JOptionPane.showMessageDialog(null,"Record not found in customer table");
            }
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fstBtn;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jSex;
    private javax.swing.JTextField jStatus;
    private javax.swing.JTextField jType;
    private javax.swing.JButton lstBtn;
    private javax.swing.JButton nxtBtn;
    private javax.swing.JButton preBtn;
    // End of variables declaration//GEN-END:variables

}
